import type { Station } from "../stationTypes";

/**
 * European airports with direct flights FROM Iberian hub airports (PT/ES catalog).
 * Shown on the map as `Airport Destination` markers. We do **not** sample outbound
 * flights or build connection maps from these airports — only hubs in
 * `portugal/airports.ts` / `spain/airports.ts` are collected.
 *
 * Regenerated by `scripts/collect-airport-connections.mjs` (and optional backfill).
 */
export const europeDestinationAirports: Station[] = [

];

