import type { CustomerInfo, Purchases } from "@revenuecat/purchases-js";
import {
  MONTHLY_PACKAGE_ID,
  PRO_ENTITLEMENT_ID,
  REVENUECAT_WEB_API_KEY,
  isRevenueCatNativeMobileKey,
  isRevenueCatTestStoreKey,
} from "@/constants/revenueCat";

/**
 * Web RevenueCat bootstrap. Mirrors the fail-soft philosophy of the mobile
 * `mobile/lib/revenueCat.ts`: configure once, never throw, and leave purchases
 * unavailable (rather than crashing the site) whenever the key is missing, the
 * SDK fails to load, or we're rendering outside a browser (prerender/SSR).
 *
 * The Web SDK is client-only: `Purchases.generateRevenueCatAnonymousAppUserId()`
 * needs `crypto`, and `configure()` touches `window`. Everything here therefore
 * bails out early when `window` is undefined so the prerender step stays safe.
 *
 * No paywall / purchase UI lives here yet — this only creates (or restores) an
 * anonymous Customer profile so the visitor shows up in the RevenueCat dashboard.
 */

/**
 * Stable per-browser RevenueCat App User ID. Persisted so returning visitors map
 * to the same RevenueCat Customer instead of spawning a new anonymous profile on
 * every reload. Format: `$RCAnonymousID:<uuid>` (generated by the SDK).
 */
export const REVENUECAT_APP_USER_ID_STORAGE_KEY = "pn_revenuecat_app_user_id";

let configureAttempted = false;
let configureSucceeded = false;
let purchasesInstance: Purchases | null = null;

/** True once configure succeeded and the SDK is usable. */
export function isRevenueCatReady(): boolean {
  return configureSucceeded;
}

/** True once configure was attempted (success or soft-failure). */
export function isRevenueCatBootstrapFinished(): boolean {
  return configureAttempted;
}

/** The configured Purchases instance, or null when unavailable. */
export function getPurchasesInstance(): Purchases | null {
  return purchasesInstance;
}

function isBrowser(): boolean {
  return typeof window !== "undefined";
}

/** Read the persisted App User ID, if any (does not create one). */
export function getStoredRevenueCatAppUserId(): string | null {
  if (typeof localStorage === "undefined") return null;
  try {
    const existing = localStorage.getItem(REVENUECAT_APP_USER_ID_STORAGE_KEY);
    return existing && existing.length >= 8 ? existing : null;
  } catch {
    return null;
  }
}

/**
 * Return a stable App User ID for this browser, creating and persisting one on
 * first visit. `generate` is the SDK's `generateRevenueCatAnonymousAppUserId`.
 */
function getOrCreateRevenueCatAppUserId(generate: () => string): string {
  const stored = getStoredRevenueCatAppUserId();
  if (stored) return stored;

  const id = generate();
  try {
    localStorage.setItem(REVENUECAT_APP_USER_ID_STORAGE_KEY, id);
  } catch {
    // Private mode / storage disabled: fall back to an ephemeral id. RevenueCat
    // will still create a profile; it just won't be stable across reloads.
  }
  return id;
}

/**
 * Configure RevenueCat once. Never throws. Returns true if the SDK is ready.
 *
 * Soft-fails (returns false) when: not in a browser, no API key configured, a
 * Test Store key is used in production, or the SDK errors while loading/config.
 */
export async function configureRevenueCat(): Promise<boolean> {
  if (configureSucceeded) return true;
  if (!isBrowser()) return false;

  configureAttempted = true;

  const apiKey = REVENUECAT_WEB_API_KEY.trim();

  if (!apiKey) {
    if (import.meta.env.DEV) {
      console.warn(
        "[revenuecat] missing VITE_REVENUECAT_WEB_API_KEY — skipping configure",
      );
    }
    return false;
  }

  if (isRevenueCatNativeMobileKey(apiKey)) {
    console.warn(
      "[revenuecat] native iOS/Android SDK keys (appl_/goog_) do not work with the Web SDK — skipping configure",
    );
    return false;
  }

  // Never let a Test Store key reach a production deployment (mirrors mobile).
  if (isRevenueCatTestStoreKey(apiKey) && import.meta.env.PROD) {
    console.warn(
      "[revenuecat] refusing to configure with a Test Store key in production",
    );
    return false;
  }

  try {
    const { Purchases, LogLevel } = await import("@revenuecat/purchases-js");

    Purchases.setLogLevel(import.meta.env.DEV ? LogLevel.Debug : LogLevel.Error);

    if (Purchases.isConfigured()) {
      purchasesInstance = Purchases.getSharedInstance();
      configureSucceeded = true;
      return true;
    }

    const appUserId = getOrCreateRevenueCatAppUserId(() =>
      Purchases.generateRevenueCatAnonymousAppUserId(),
    );

    purchasesInstance = Purchases.configure({ apiKey, appUserId });
    configureSucceeded = true;
    return true;
  } catch (error) {
    configureSucceeded = false;
    purchasesInstance = null;
    console.warn("[revenuecat] configure failed", error);
    return false;
  }
}

/** Fetch the current customer info, or null if unavailable. Never throws. */
export async function getCustomerInfoSafe(): Promise<CustomerInfo | null> {
  if (!configureSucceeded || !purchasesInstance) return null;
  try {
    return await purchasesInstance.getCustomerInfo();
  } catch (error) {
    console.warn("[revenuecat] getCustomerInfo failed", error);
    return null;
  }
}

/** True if the `iberian.travel Pro` entitlement is active on this customer. */
export function isProEntitlementActive(
  info: CustomerInfo | null | undefined,
): boolean {
  if (!info) return false;
  return Boolean(info.entitlements.active[PRO_ENTITLEMENT_ID]);
}

export { PRO_ENTITLEMENT_ID, MONTHLY_PACKAGE_ID };
export type { CustomerInfo };
