/**
 * Upsert Europe destination airport stations derived from connection sampling.
 * See src/lib/europeAirportDestinations.ts for inclusion rules.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import {
  destinationAirportDisplayName,
  isEuropeDestinationCandidate,
} from "../../src/lib/europeAirportDestinations.ts";
import { AIRPORT_DESTINATION_TYPE } from "../../src/lib/airportTypes.ts";
import { loadAirportCatalog } from "./airportCatalog.mjs";

const EUROPE_AIRPORTS_REL = "src/data/europe/airports.ts";

function escapeTsString(value) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function formatStationEntry(station) {
  return `  {
    name: "${escapeTsString(station.name)}",
    country: "${station.country}",
    lines: ["${station.iata}"],
    types: ["${AIRPORT_DESTINATION_TYPE}"],
    lat: ${station.lat},
    lng: ${station.lng},
  }`;
}

/**
 * @param {string} rootDir
 * @param {Iterable<string>} destinationIatas
 * @param {Record<string, { name: string; country: string; lat: number; lng: number }>} coordinates
 * @param {{ dryRun?: boolean }} [options]
 */
export function upsertEuropeDestinationAirports(
  rootDir,
  destinationIatas,
  coordinates,
  options = {},
) {
  const { dryRun = false } = options;
  const hubIatas = new Set(
    loadAirportCatalog(rootDir)
      .map((airport) => airport.iata?.toUpperCase())
      .filter(Boolean),
  );

  const byIata = new Map();
  for (const raw of destinationIatas) {
    const iata = String(raw ?? "")
      .trim()
      .toUpperCase();
    const coords = coordinates[iata];
    if (!coords) continue;
    if (!isEuropeDestinationCandidate(iata, coords, hubIatas)) continue;

    const iso = String(coords.country ?? "")
      .trim()
      .toUpperCase();
    if (!iso || iso.length !== 2) continue;

    byIata.set(iata, {
      iata,
      name: destinationAirportDisplayName(iata, coords.name || iata),
      country: iso.toLowerCase(),
      lat: coords.lat,
      lng: coords.lng,
    });
  }

  const stations = [...byIata.values()].sort((a, b) => a.iata.localeCompare(b.iata));
  const outPath = join(rootDir, EUROPE_AIRPORTS_REL);
  const body = `import type { Station } from "../stationTypes";

/**
 * European airports with direct flights FROM Iberian hub airports (PT/ES catalog).
 * Shown on the map as \`Airport Destination\` markers. We do **not** sample outbound
 * flights or build connection maps from these airports — only hubs in
 * \`portugal/airports.ts\` / \`spain/airports.ts\` are collected.
 *
 * Regenerated by \`scripts/collect-airport-connections.mjs\` (and optional backfill).
 */
export const europeDestinationAirports: Station[] = [
${stations.map(formatStationEntry).join(",\n")}
];
`;

  if (!dryRun) {
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, `${body}\n`);
  }

  return { path: outPath, count: stations.length, iatas: stations.map((s) => s.iata) };
}

export function collectDestinationIatasFromManifest(manifest) {
  const iatas = new Set();
  for (const entry of Object.values(manifest?.airports ?? {})) {
    for (const connection of entry.connections ?? []) {
      const iata = connection?.iata?.trim?.().toUpperCase?.();
      if (iata) iatas.add(iata);
    }
  }
  return iatas;
}
