/**
 * Two maps per non-Iberian airport:
 *   1. Iberian flights only (`{iata}-{place}-iberia.png`)
 *   2. All flights (`{iata}-{place}.png`)
 * Departures runs add one missing Iberian map (no flight API). Flight APIs up:
 * add or refresh one all-flights map without replacing the Iberian one
 * (airports whose all-flights sample missed Iberian destinations are redrawn first).
 * Compact station pages exist only once both maps are present.
 */
import { existsSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { stationToSlug } from "./socialCard.mjs";
import {
  countIberianConnectionDestinations,
  coverageFromExternalMapRows,
  externalAirportDisplayName,
  externalMapFilename,
  externalMapPublicPath,
  externalSpotlightLimit,
  formatExternalAirportMapsLog,
  hasAllFlightsMap,
  hasBothExternalMaps,
  hasIberianMap,
  IBERIAN_INBOUND_PROVIDER,
  normalizeExternalAirportRow,
  pickExternalAirportForRun,
  rankExternalAirportsFromManifest,
} from "../../src/lib/externalAirportSpotlight.ts";

export {
  externalSpotlightLimit,
  formatExternalAirportMapsLog,
  hasAllFlightsMap,
  hasBothExternalMaps,
  hasIberianMap,
  normalizeExternalAirportRow,
};
import { loadAirportCatalog } from "./airportCatalog.mjs";
import { getFlightLineColor, getFlightLineWeight } from "../../server/lib/airportIata.ts";
import { formatCountryName } from "../../server/lib/countryName.ts";

export const EXTERNAL_MAPS_REL = "public/maps/airports/external";
export const EXTERNAL_STORE_REL = "data/external-airport-connection-maps.json";
const PAGE_IATAS_REL = "src/data/externalAirportPageIatas.ts";

export function externalMapsDir(rootDir) {
  return join(rootDir, EXTERNAL_MAPS_REL);
}

export function externalStorePath(rootDir) {
  return join(rootDir, EXTERNAL_STORE_REL);
}

export function loadExternalAirportMapsStore(rootDir) {
  try {
    const raw = JSON.parse(readFileSync(externalStorePath(rootDir), "utf8"));
    const airports = Array.isArray(raw?.airports) ? raw.airports : [];
    let dirty = false;
    const migrated = airports.map((row) => {
      const next = migrateLegacyIberianRow(rootDir, row);
      if (next !== row) dirty = true;
      return next;
    });
    const store = {
      updatedAt: typeof raw?.updatedAt === "string" ? raw.updatedAt : null,
      airports: migrated,
    };
    if (dirty) saveExternalAirportMapsStore(rootDir, store);
    return store;
  } catch {
    return { updatedAt: null, airports: [] };
  }
}

export function saveExternalAirportMapsStore(rootDir, store) {
  const outPath = externalStorePath(rootDir);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, `${JSON.stringify(store, null, 2)}\n`);
  writeExternalAirportPageIatas(rootDir, store);
  return outPath;
}

export function writeExternalAirportPageIatas(rootDir, store) {
  const iatas = (store?.airports ?? [])
    .map((row) => normalizeExternalAirportRow(row))
    .filter((row) => hasBothExternalMaps(row))
    .map((row) => String(row.iata ?? "").trim().toUpperCase())
    .filter(Boolean)
    .sort();
  const unique = [...new Set(iatas)];
  const body = `/** Auto-generated by scripts/lib/externalAirportConnectionMaps.mjs — do not edit. */\nexport const EXTERNAL_AIRPORT_PAGE_IATAS: readonly string[] = ${JSON.stringify(unique, null, 2)};\n`;
  const outPath = join(rootDir, PAGE_IATAS_REL);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, body);
  return outPath;
}

function mapBasename(publicPath) {
  return basename(String(publicPath ?? ""));
}

function replaceMapFile(mapsDir, fromNames, destName) {
  const dest = join(mapsDir, destName);
  for (const name of fromNames) {
    if (!name || name === destName) continue;
    const src = join(mapsDir, name);
    if (!existsSync(src)) continue;
    if (!existsSync(dest)) renameSync(src, dest);
    else if (src !== dest) unlinkSync(src);
  }
}

function migrateLegacyIberianRow(rootDir, row) {
  const normalized = normalizeExternalAirportRow(row);
  const iata = String(normalized.iata ?? "").trim().toUpperCase();
  const name = normalized.stationName || normalized.slug || iata;
  const slug = normalized.slug;
  const mapsDir = externalMapsDir(rootDir);

  if (slug && hasIberianMap(normalized) && !hasAllFlightsMap(normalized)) {
    const dest = join(mapsDir, `${slug}-iberian-connections.png`);
    const legacy = join(mapsDir, `${slug}-connections.png`);
    if (existsSync(legacy) && !existsSync(dest)) {
      renameSync(legacy, dest);
    }
  }

  if (!iata) return normalized;

  const iberianPath = externalMapPublicPath(iata, name, "iberian");
  const iberianNames = [
    mapBasename(normalized.iberianMapImage),
    slug && `${slug}-iberian-connections.png`,
    !hasAllFlightsMap(normalized) && slug ? `${slug}-connections.png` : null,
  ].filter(Boolean);
  replaceMapFile(mapsDir, iberianNames, mapBasename(iberianPath));

  const next = { ...normalized, iberianMapImage: hasIberianMap(normalized) ? iberianPath : normalized.iberianMapImage };

  if (hasAllFlightsMap(normalized)) {
    const allPath = externalMapPublicPath(iata, name, "all");
    const allNames = [
      mapBasename(normalized.mapImage),
      slug && `${slug}-connections.png`,
    ].filter(Boolean);
    replaceMapFile(mapsDir, allNames, mapBasename(allPath));
    next.mapImage = allPath;
  }

  return next;
}

function hubIataSet(rootDir) {
  return new Set(
    loadAirportCatalog(rootDir)
      .map((airport) => airport.iata?.toUpperCase())
      .filter(Boolean),
  );
}

export function chooseExternalAirportForRun(
  rootDir,
  manifest,
  coordinates,
  store,
  options = {},
) {
  const ranked = rankExternalAirportsFromManifest(
    manifest,
    hubIataSet(rootDir),
    coordinates,
  );
  const sampled = coverageFromExternalMapRows(store?.airports ?? []);
  const pick = pickExternalAirportForRun(ranked, sampled, options);
  if (!pick) return { ranked, pick: null, coords: null, stationName: null, slug: null };
  const coords = coordinates[pick.iata];
  const stationName = externalAirportDisplayName(pick.iata, coords);
  return {
    ranked,
    pick,
    coords,
    stationName,
    slug: stationToSlug(stationName),
  };
}

function hubNetwork(manifest) {
  const byIata = new Map();
  for (const entry of Object.values(manifest?.fallbackAirports ?? {})) {
    const iata = entry.iata?.trim().toUpperCase();
    if (iata) byIata.set(iata, entry);
  }
  for (const entry of Object.values(manifest?.airports ?? {})) {
    const iata = entry.iata?.trim().toUpperCase();
    if (iata) byIata.set(iata, entry);
  }
  return [...byIata.values()];
}

function buildIberianInboundEntry({
  pick,
  coords,
  stationName,
  slug,
  manifest,
  coordinates,
}) {
  const dest = pick.iata;
  const connections = [];
  for (const hub of hubNetwork(manifest)) {
    const originIata = hub.iata?.trim().toUpperCase();
    if (!originIata || originIata === dest) continue;
    const inbound = (hub.connections ?? []).find(
      (connection) => connection.iata?.trim().toUpperCase() === dest,
    );
    if (!inbound) continue;
    const origin = hub.origin;
    if (!origin || !Number.isFinite(origin.lat) || !Number.isFinite(origin.lng)) continue;
    const hubCoords = coordinates[originIata];
    const flightCount = inbound.flightCount || 0;
    connections.push({
      iata: originIata,
      name: hub.stationName || hubCoords?.name || originIata,
      country: formatCountryName(hubCoords?.country || ""),
      lat: origin.lat,
      lng: origin.lng,
      flightCount,
      flights: inbound.flights ?? [],
      lineColor: getFlightLineColor(flightCount),
      lineWeight: getFlightLineWeight(flightCount),
    });
  }
  connections.sort(
    (a, b) => b.flightCount - a.flightCount || a.name.localeCompare(b.name),
  );
  if (!connections.length) return null;
  return {
    stationName,
    slug,
    iata: dest,
    origin: { lat: coords.lat, lng: coords.lng },
    sampledFlights: pick.iberianFlightCount,
    connections,
    topDestinations: connections.slice(0, 10),
    mapImage: externalMapPublicPath(dest, stationName, "iberian"),
  };
}

function existingMapRow(store, iata) {
  const code = String(iata ?? "").toUpperCase();
  const row =
    (store?.airports ?? []).find((entry) => String(entry.iata ?? "").toUpperCase() === code) ??
    null;
  return row ? normalizeExternalAirportRow(row) : null;
}

function mergeAirportRow(store, patch) {
  const airports = [...(store.airports ?? [])];
  const index = airports.findIndex((entry) => entry.iata === patch.iata);
  const previous = index >= 0 ? normalizeExternalAirportRow(airports[index]) : {};
  const merged = { ...previous, ...patch };
  if (index >= 0) airports[index] = merged;
  else airports.push(merged);
  return {
    updatedAt: patch.iberianSampledAt || patch.sampledAt || previous.updatedAt || null,
    airports,
  };
}

async function persistExternalAirportMap({
  rootDir,
  store,
  entry,
  pick,
  coords,
  stationName,
  slug,
  provider,
  periodId,
  siteUrl,
  basemapMode,
  renderAirportConnectionsMap,
  kind,
}) {
  const publicPath = externalMapPublicPath(pick.iata, stationName, kind);
  entry.mapImage = publicPath;
  const png = await renderAirportConnectionsMap(entry, {
    siteUrl,
    basemapMode,
    showStationPageUrl: true,
    connectionScope: kind,
  });
  const mapsDir = externalMapsDir(rootDir);
  mkdirSync(mapsDir, { recursive: true });
  writeFileSync(join(mapsDir, externalMapFilename(pick.iata, stationName, kind)), png.buffer);

  const sampledAt = new Date().toISOString();
  const patch = {
    iata: pick.iata,
    stationName,
    slug,
    country: coords.country ?? "",
    iberianFlightCount: pick.iberianFlightCount,
  };
  if (kind === "iberian") {
    Object.assign(patch, {
      iberianMapImage: publicPath,
      iberianDestinationCount: entry.connections.length,
      iberianSampledFlights: entry.sampledFlights,
      iberianSampledAt: sampledAt,
      iberianPeriodId: periodId,
      iberianBasemapId: png.basemapId,
    });
  } else {
    Object.assign(patch, {
      mapImage: publicPath,
      destinationCount: entry.connections.length,
      allFlightsIberianDestinationCount: countIberianConnectionDestinations(entry.connections),
      sampledFlights: entry.sampledFlights,
      sampledAt,
      periodId,
      provider,
      basemapId: png.basemapId,
    });
  }

  const nextStore = mergeAirportRow(store, patch);
  saveExternalAirportMapsStore(rootDir, nextStore);
  const label = `${stationName} (${pick.iata})`;
  const action =
    kind === "iberian" ? "Iberian flights map" : "all-flights map";
  console.log(
    `External spotlight ${label}: ${entry.connections.length} destinations` +
      ` (${pick.iberianFlightCount} Iberian flights in) ${action} via ${provider} (${png.basemapId})`,
  );
  return { store: nextStore, skipped: false, skipReason: null, pick, entry };
}

function iberianInboundForChosen(chosen, manifest, coordinates) {
  return buildIberianInboundEntry({
    pick: chosen.pick,
    coords: chosen.coords,
    stationName: chosen.stationName,
    slug: chosen.slug,
    manifest,
    coordinates,
  });
}

function unionAllFlightsWithIberianInbound(outbound, inbound) {
  if (!inbound?.connections?.length) return outbound;
  const byIata = new Map();
  for (const connection of outbound.connections ?? []) {
    const iata = connection.iata?.trim().toUpperCase();
    if (iata) byIata.set(iata, connection);
  }
  let added = 0;
  for (const connection of inbound.connections) {
    const iata = connection.iata?.trim().toUpperCase();
    if (!iata || byIata.has(iata)) continue;
    byIata.set(iata, connection);
    added += 1;
  }
  if (!added) return outbound;
  const connections = [...byIata.values()].sort(
    (a, b) => b.flightCount - a.flightCount || a.name.localeCompare(b.name),
  );
  return {
    ...outbound,
    connections,
    topDestinations: connections.slice(0, 10),
  };
}

/**
 * One external map per collect step. Iberian and all-flights maps are kept separately.
 * APIs down: Iberian map for the next airport that is missing one.
 * APIs up: all-flights map (without replacing the Iberian image).
 */
export async function sampleExternalAirportConnectionMap(options) {
  const {
    rootDir,
    manifest,
    coordinates,
    fetchDepartures,
    resolveMissingCoordinates,
    buildAirportConnections,
    renderAirportConnectionsMap,
    siteUrl,
    basemapMode = "osm",
    periodId = null,
    dryRun = false,
    skip = false,
    skipReason = null,
    flightApisAvailable = true,
    forceIata = null,
  } = options;

  const store = loadExternalAirportMapsStore(rootDir);
  if (skip) {
    return { store, skipped: true, skipReason, pick: null };
  }

  const persist = (chosen, entry, provider, kind) =>
    persistExternalAirportMap({
      rootDir,
      store,
      entry,
      pick: chosen.pick,
      coords: chosen.coords,
      stationName: chosen.stationName,
      slug: chosen.slug,
      provider,
      periodId,
      siteUrl,
      basemapMode,
      renderAirportConnectionsMap,
      kind,
    });

  const chosen = chooseExternalAirportForRun(rootDir, manifest, coordinates, store, {
    flightApisAvailable,
    forceIata,
  });
  if (!chosen.pick || !chosen.coords) {
    return {
      store,
      skipped: true,
      skipReason: flightApisAvailable ? "no-external-destination" : "no-unmapped-external",
      pick: null,
    };
  }

  const { pick, coords, stationName } = chosen;
  const label = `${stationName} (${pick.iata})`;
  const existing = existingMapRow(store, pick.iata);

  if (dryRun) {
    const intent = !flightApisAvailable
      ? `Iberian flights map (${pick.iberianFlightCount} Iberian flights)`
      : existing && hasAllFlightsMap(existing)
        ? `refresh all-flights map`
        : `all-flights map (${pick.iberianFlightCount} Iberian flights in)`;
    console.log(`[dry-run] External spotlight: ${label} — ${intent}`);
    return { store, skipped: true, skipReason: "dry-run", pick };
  }

  if (!flightApisAvailable) {
    const inbound = iberianInboundForChosen(chosen, manifest, coordinates);
    if (!inbound) {
      console.warn(`External spotlight ${label}: no mappable Iberian destinations`);
      return { store, skipped: true, skipReason: "no-connections", pick };
    }
    return persist(chosen, inbound, IBERIAN_INBOUND_PROVIDER, "iberian");
  }

  const synthetic = {
    stationName,
    slug: chosen.slug,
    iata: pick.iata,
    name: coords.name || pick.iata,
    lat: coords.lat,
    lng: coords.lng,
    countryCode: "pt",
  };

  try {
    const sample = await fetchDepartures(pick.iata, 100);
    const destIatas = [
      ...new Set(
        sample.flights
          .map((flight) => flight.arrival?.iata?.trim().toUpperCase())
          .filter((iata) => iata && iata !== pick.iata),
      ),
    ];
    await resolveMissingCoordinates(destIatas.filter((iata) => !coordinates[iata]));
    const outbound = buildAirportConnections(synthetic, sample.flights, coordinates);
    if (!outbound?.connections?.length) {
      throw new Error("outbound sample returned no mappable destinations");
    }
    const inbound = iberianInboundForChosen(chosen, manifest, coordinates);
    const entry = unionAllFlightsWithIberianInbound(outbound, inbound);
    const added = entry.connections.length - outbound.connections.length;
    if (added > 0) {
      console.log(
        `External spotlight ${label}: added ${added} Iberian destination(s) the outbound sample missed`,
      );
    }
    return persist(chosen, entry, sample.provider, "all");
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (!existing || !hasIberianMap(existing)) {
      console.warn(
        `Flight APIs are out of monthly quota, so I'll build the Iberian flights map from connections we already have: ${label}. (${message})`,
      );
      const inbound = iberianInboundForChosen(chosen, manifest, coordinates);
      if (!inbound) {
        console.warn(`External spotlight ${label}: no mappable destinations`);
        return { store, skipped: true, skipReason: "no-connections", pick };
      }
      return persist(chosen, inbound, IBERIAN_INBOUND_PROVIDER, "iberian");
    }

    console.warn(
      `External spotlight ${label}: all-flights sample failed (${message}); keeping existing maps.`,
    );

    if (forceIata) {
      return {
        store,
        skipped: true,
        skipReason: "keep-existing",
        pick,
      };
    }

    const fallback = chooseExternalAirportForRun(rootDir, manifest, coordinates, store, {
      flightApisAvailable: false,
    });
    if (!fallback.pick || !fallback.coords || fallback.pick.iata === pick.iata) {
      return {
        store,
        skipped: true,
        skipReason: "keep-existing",
        pick,
      };
    }

    const fallbackLabel = `${fallback.stationName} (${fallback.pick.iata})`;
    const inbound = iberianInboundForChosen(fallback, manifest, coordinates);
    if (!inbound) {
      console.warn(`External spotlight ${fallbackLabel}: no mappable Iberian destinations`);
      return {
        store,
        skipped: true,
        skipReason: "keep-existing",
        pick,
      };
    }
    console.warn(
      `Drawing the Iberian flights map for ${fallbackLabel} while APIs are down.`,
    );
    return persist(fallback, inbound, IBERIAN_INBOUND_PROVIDER, "iberian");
  }
}

