import { readFileSync, writeFileSync } from "node:fs";

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export function pexelsPhotoIdFromUrl(url) {
  const match = url.match(/pexels\.com\/photos\/(\d+)\//i);
  return match?.[1] ?? null;
}

export function parsePexelsCredits(ts) {
  const map = {};
  const block = ts.match(/export const pexelsPhotoCredits[^=]*=\s*\{([\s\S]*?)\};/);
  if (!block) return map;
  for (const match of block[1].matchAll(
    /"(\d+)":\s*\{\s*photographer:\s*"([^"]*)",\s*photographerUrl:\s*"([^"]*)",\s*photoPageUrl:\s*"([^"]*)",?\s*\}/g,
  )) {
    map[match[1]] = {
      photographer: match[2],
      photographerUrl: match[3],
      photoPageUrl: match[4],
    };
  }
  return map;
}

export function writePexelsCredits(creditsPath, map) {
  const lines = Object.entries(map)
    .sort(([a], [b]) => Number(a) - Number(b))
    .map(
      ([id, credit]) =>
        `  "${id}": {
    photographer: ${JSON.stringify(credit.photographer)},
    photographerUrl: ${JSON.stringify(credit.photographerUrl)},
    photoPageUrl: ${JSON.stringify(credit.photoPageUrl)},
  },`,
    );
  const content = `/** Photographer credits for Pexels photos, keyed by photo id. Generated by scripts/sync-pexels-credits.mjs */
export type PexelsPhotoCredit = {
  photographer: string;
  photographerUrl: string;
  photoPageUrl: string;
};

export const pexelsPhotoCredits: Record<string, PexelsPhotoCredit> = {
${lines.join("\n")}
};
`;
  writeFileSync(creditsPath, content);
}

export function upsertPexelsCredit(map, photoId, credit) {
  if (!photoId || !credit?.photographer) return;
  map[photoId] = {
    photographer: credit.photographer,
    photographerUrl: credit.photographerUrl ?? "",
    photoPageUrl: credit.photoPageUrl ?? "",
  };
}

export function creditFromPexelsPhoto(photo) {
  if (!photo?.photographer) return null;
  return {
    photographer: photo.photographer,
    photographerUrl: photo.photographer_url ?? "",
    photoPageUrl: photo.url ?? "",
  };
}

export async function fetchPexelsPhotoCredit(photoId, apiKey) {
  for (let attempt = 0; attempt < 5; attempt++) {
    const res = await fetch(`https://api.pexels.com/v1/photos/${photoId}`, {
      headers: { Authorization: apiKey },
    });
    if (res.status === 429) {
      await sleep(2000 * (attempt + 1));
      continue;
    }
    if (!res.ok) {
      throw new Error(`Pexels ${res.status} for photo ${photoId}`);
    }
    const photo = await res.json();
    return creditFromPexelsPhoto(photo);
  }
  throw new Error(`Pexels 429 for photo ${photoId}`);
}

export function loadPexelsCredits(creditsPath) {
  try {
    return parsePexelsCredits(readFileSync(creditsPath, "utf8"));
  } catch {
    return {};
  }
}
