/** Auto-generated by scripts/lib/externalAirportConnectionMaps.mjs — do not edit. */
export const EXTERNAL_AIRPORT_PAGE_IATAS: readonly string[] = [
  "AMS",
  "BRU",
  "CDG",
  "FCO",
  "FRA",
  "IBZ",
  "LGW",
  "LHR",
  "LPA",
  "MAN",
  "MUC",
  "MXP",
  "ORY",
  "PMI",
  "TFN",
  "ZRH"
];
